//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/UIControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIControls"",
    ""maps"": [
        {
            ""name"": ""GeneralUI"",
            ""id"": ""f1305a16-54f8-43d7-a308-784d8f52749e"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""e31a9796-dbb5-4ca9-8cf3-6d2579a011ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a606e96c-7a8b-4b8c-9851-d77008d68df6"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GeneralUI
        m_GeneralUI = asset.FindActionMap("GeneralUI", throwIfNotFound: true);
        m_GeneralUI_Pause = m_GeneralUI.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GeneralUI
    private readonly InputActionMap m_GeneralUI;
    private IGeneralUIActions m_GeneralUIActionsCallbackInterface;
    private readonly InputAction m_GeneralUI_Pause;
    public struct GeneralUIActions
    {
        private @UIControls m_Wrapper;
        public GeneralUIActions(@UIControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_GeneralUI_Pause;
        public InputActionMap Get() { return m_Wrapper.m_GeneralUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralUIActions set) { return set.Get(); }
        public void SetCallbacks(IGeneralUIActions instance)
        {
            if (m_Wrapper.m_GeneralUIActionsCallbackInterface != null)
            {
                @Pause.started -= m_Wrapper.m_GeneralUIActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_GeneralUIActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_GeneralUIActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_GeneralUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public GeneralUIActions @GeneralUI => new GeneralUIActions(this);
    public interface IGeneralUIActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
